# @package _global_

# default parameters for AutoencoderKLAD model
model_name: "AutoencoderKLAD"

model: 
  learning_rate: 0.001 
  beta: 1
  perceptual_weight: 1
  disc_weight: 1
  in_channels: 1
  out_channels: 1
  num_res_blocks: 2
  num_channels: [32, 64, 64, 64]
  latent_channels: 3
  norm_num_groups: 32
  norm_eps: 0.000001

encoder:
  default:
    _target_: autoencoders.architectures.cnn.VariationalEncoder
    enc_dist:
      _target_: autoencoders.base.distributions.Normal
    in_channels: ${model.in_channels}
    out_channels: ${model.out_channels}
    num_res_blocks: ${model.num_res_blocks}
    num_channels: ${model.num_channels}
    latent_channels: ${model.latent_channels}
    norm_num_groups: ${model.norm_num_groups}
    norm_eps: ${model.norm_eps}
    bias: True
    non_linear: True

decoder:
  default:
    _target_: autoencoders.architectures.cnn.Decoder
    dec_dist:
      _target_: autoencoders.base.distributions.Normal
    in_channels: ${model.in_channels}
    out_channels: ${model.out_channels}
    num_res_blocks: ${model.num_res_blocks}
    num_channels: ${model.num_channels}
    latent_channels: ${model.latent_channels}
    norm_num_groups: ${model.norm_num_groups}
    norm_eps: ${model.norm_eps}
    bias: True
    non_linear: True

n_discriminator: 
  disc_in_channels: 3
  disc_num_layers: 3