# @package _global_

# default parameters for vaebase model
model_name: "vaebase"

model: 
  beta: 1
  in_channels: 1
  out_channels: 1


encoder:
  default:
    _target_: autoencoders.architectures.cnn.VariationalEncoder
    enc_dist:
      _target_: autoencoders.base.distributions.Normal
    in_channels: ${model.in_channels}
    out_channels: ${model.out_channels}
    bias: True
    non_linear: True

decoder:
  default:
    _target_: autoencoders.architectures.cnn.Decoder
    dec_dist:
      _target_: autoencoders.base.distributions.Normal
    in_channels: ${model.in_channels}
    out_channels: ${model.out_channels}
    bias: True
    non_linear: True
