# dataset
dataset: "una"

data_path: "/path/to/your/data" # TODO: set to your data path
data_config_path: "./configs/precalc/training.yaml"
vae_path: "/path/to/your/vae_model.ckpt"

# save and load
results_dir: "./results/Unet"
pretrained: 

# model config: 
model: UNet 
in_channels: 3
input_dims: [160, 160, 160]
num_channels: [128, 256, 256]
attention_levels: [False, False, True]
num_res_blocks: 1
num_head_channels: 256
num_frames: 20
frame_interval: 3
fixed_spatial: False
image_size: 128 
num_sampling_steps: 1000
learn_sigma: True 
labels: False 
cond: False


# model speedup
use_compile: False
use_fp16: False

# train config:
save_ceph: True 
learning_rate: 1e-4
ckpt_every: 20000
clip_max_norm: 0.1
start_clip_iter: 0 
local_batch_size: 10 
max_epochs: 2000
global_seed: 3407
num_workers: 4
log_every: 100
lr_warmup_steps: 0
resume_from_checkpoint: 
gradient_accumulation_steps: 1 # TODO
patience: 20 
cohort: 'healthy'

# low VRAM and speed up training
mixed_precision: False
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False